# This file configures pre-commit hooks for the repository.
# It defines the tools and checks that will run automatically before each
# commit, helping to enforce code quality, formatting, and best practices.
# For more information, see:
#   https://pre-commit.com/
---
fail_fast: false
minimum_pre_commit_version: "2.6.0"

ci:
  autofix_commit_msg: 'chore(pre-commit.ci): Auto fixes [...]'
  autoupdate_commit_msg: 'chore(pre-commit.ci): Auto update of pre-commit hooks'
  skip:
    - terraform_fmt_docker
    - terraform_validate_docker
    - terraform_tflint_docker
    - terraform_docs_docker
    - terraform_checkov_docker
    - terraform_trivy_docker

repos:
  # Fork from https://github.com/antonbabenko/pre-commit-terraform
  # His does not yet use docker images
  - repo: https://github.com/actuarysailor/pre-commit-terraform
    rev: "1815705d890046e053875e8b75e30965f9fa62e9"
    hooks:
      - id: terraform_fmt_docker
      - id: terraform_validate_docker
      - id: terraform_tflint_docker
      - id: terraform_docs_docker
      - id: terraform_checkov_docker
      - id: terraform_trivy_docker

  # May be easier to expand the antonbabenko repo to do this since it installs
  # all these anyways
  # - repo: https://github.com/tofuutils/pre-commit-opentofu
  #   rev: v2.2.1  # Use the latest stable version
  #   hooks:
  #     - id: tofu_fmt
  #     - id: tofu_validate
  #     - id: tofu_tflint
  #     - id: tofu_docs
  #     - id: tofu_checkov
  #     - id: tofu_trivy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the latest stable version
    hooks:
      # - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  # Optionally, add yamllint for YAML files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1  # Use the latest stable version
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint-fix
